branch_status:
  url: /branch/:git_branch_slug/status
  param: { module: branch, action: status }
  options:
    segment_separators: [/]

delayed_all_launch:
  url: /delayed/all/launch
  params: { module: delayed, action: launch }
